### ISSUE TITLE
Cannot read property 'headersSent' of undefined

### ISSUE THREAD

**Issue by marcus-sa** [pillarjs/finalhandler#21]
I keep getting this error and from the log I can see that Express is using this module, and I have no clue on how to solve it.

```
/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/finalhandler/index.js:239
[1]   return typeof res.headersSent !== 'boolean'
[1]                     ^
[1] 
[1] TypeError: Cannot read property 'headersSent' of undefined
[1]     at headersSent (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/finalhandler/index.js:239:21)
[1]     at /home/sentinel/Gitlab/stormcms-engine-v2/node_modules/finalhandler/index.js:92:17
[1]     at /home/sentinel/Gitlab/stormcms-engine-v2/node_modules/express/lib/router/index.js:635:15
[1]     at next (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/express/lib/router/index.js:210:14)
[1]     at Function.handle (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/express/lib/router/index.js:174:3)
[1]     at Function.handle (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/express/lib/application.js:174:10)
[1]     at app (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/express/lib/express.js:39:9)
[1]     at Object.<anonymous> (/home/sentinel/Gitlab/stormcms-engine-v2/src/server.js:104:1)
[1]     at Module._compile (module.js:635:30)
[1]     at loader (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:554:32)
[1]     at tryModuleLoad (module.js:497:12)
[1]     at Module._load (module.js:489:3)
[1]     at Function.module._load (/home/sentinel/Gitlab/stormcms-engine-v2/node_modules/piping/lib/piping.js:218:16)
[1]     at Module.require (module.js:579:17)
```

**Comment by stratosgear** [comment]
Same here, while using latest version (v3) of feathersJs :scratch-head:

**Comment by dougwilson** [comment]
Thanks for the report, sorry I didn't see it earlier. Can one of you provide the following information?

1. Version of Node.js
2. Version of this module
3. Complete code to run to reproduce the issue
4. Instructions on how to replicate

Thanks!

**Comment by stratosgear** [comment]
```
node --version
v9.5.0

finalhandler
1.1.0
```
You could try to pull the repo I'm trying to fix:

https://github.com/stratosgear/feathers-vuejs

If you clone, then `npm install` and 'npm start' you should get:

```

> plumage@0.2.0 start /mnt/data/projects/feathers-vuejs
> babel-node src/

/mnt/data/projects/feathers-vuejs/node_modules/finalhandler/index.js:239
  return typeof res.headersSent !== 'boolean'
                    ^

TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (/mnt/data/projects/feathers-vuejs/node_modules/finalhandler/index.js:239:21)
    at /mnt/data/projects/feathers-vuejs/node_modules/finalhandler/index.js:92:17
    at Function.handle (/mnt/data/projects/feathers-vuejs/node_modules/express/lib/application.js:170:5)
    at Function.app (/mnt/data/projects/feathers-vuejs/node_modules/express/lib/express.js:39:9)
    at Function.configure (/mnt/data/projects/feathers-vuejs/node_modules/@feathersjs/feathers/lib/application.js:59:8)
    at Object.<anonymous> (/mnt/data/projects/feathers-vuejs/src/app.js:25:4)
    at Module._compile (module.js:660:30)
    at loader (/mnt/data/projects/feathers-vuejs/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/data/projects/feathers-vuejs/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/data/projects/feathers-vuejs/src/index.js:3:13)
    at Module._compile (module.js:660:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! plumage@0.2.0 start: `babel-node src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the plumage@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stratos/.npm/_logs/2018-02-19T21_38_52_746Z-debug.log
```

**Comment by dougwilson** [comment]
Thanks @stratosgear I was able to reproduce the issue with your example. There is a lot going on here, though, so I won't be able to look at it right now since I was just about to leave. Is there any way you can trim down the reproduction to only using this module? The stack trace doesn't indicated an error in this module -- it is indicating that the function  this module is exporting is being called without the required `res` argument:
```js
node -pe 'require("finalhandler")()()'
node_modules\finalhandler\index.js:239
  return typeof res.headersSent !== 'boolean'
                   ^

TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (C:\Users\dougw\GitHub\feathers-vuejs\node_modules\finalhandler\index.js:239:20)
    at C:\Users\dougw\GitHub\feathers-vuejs\node_modules\finalhandler\index.js:92:17
    at [eval]:1:26
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:353:27)
    at run (bootstrap_node.js:122:11)
    at run (bootstrap_node.js:389:7)
```

If you provide the required `res` argument to this module's export, does that resolve the issue?

**Comment by stratosgear** [comment]
from what i googled around (https://github.com/nodejs/node/issues/15226) you might get this if the stream is already closed...? so `res` is an undefined? 

I'm over my head trying to port that old repo to the latest version of FeatherJs and I do not feel confident I would be able to provide a minimal working example of this, I'm afraid... :(

**Comment by dougwilson** [comment]
But the error happens on `nom start` without making a request yet, so I don't think it's related to actually making a request, right? The `finalhandler` module takes two required arguments to construct -- `req` and `res`. What request is happening during `npm start` that would provide with a `req` and `res` to even construct a new `finalhandler` instance?

**Comment by dougwilson** [comment]
I went through `src/app` and commented out each line one-by-one trying to see when the error stopped. It went away commenting out the line `.configure(rest())` -- what does that line do?

**Comment by dougwilson** [comment]
Tracing it through, `.configure(fn)` simply invokes `fn` with `this` set to the same context, so similar to `rest().call(app)`. The `rest()` call is the function exported by the `@feathersjs/express` module, which looks like it is decorating an Express app with some extra functionality, but then the express app is immediately being invoked by that `.configure` call without providing a request and response object, which eventually leads down to this module getting constructed without a request and response object and then invoked.

Pretty much boils down to the following happening:
```
$ node -pe 'require("express")()()'
node_modules\finalhandler\index.js:239
  return typeof res.headersSent !== 'boolean'
                   ^

TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (node_modules\finalhandler\index.js:239:20)
```

Notice that double function call. That second function call shouldn't be there, so you just need to get that sorted out and the issue should go away 👍 I'm not familiar with how feathers is working or how to put everything together, but that is what is causing the error, which is just some logic errors somewhere in the code that eventually calls into this module without providing any arguments.

**Comment by stratosgear** [comment]
Wow plenty of things to work with.  Let me see what I can do here...

Thanks for the investigative work!

**Comment by dougwilson** [comment]
No problem! I'll look into adding a guard when constructing the finalhander to validate that at least some object was provided for req and res to get a better error, though the error would have just been different in this case rather than there being no error. Since the constructor is called with every request, I just need to check what the impact of adding that check is.

**Comment by stratosgear** [comment]
OK, that '.configure(rest())` call was extraneous and had to go!

So in my case, it was a misuse of the library. 

You were very helpfull, in pointing me the right way.  Thanks!

**Comment by dougwilson** [comment]
No problem! Even if I'm not familiar with feathers, etc. it's easy to ve helpful in figuring it out when I can reproduce and debug through it :+1: thanks for providing that code!

**Comment by BienfaitM** [comment]
helllo 
i do need some help for running my express project.
i have try to debug but i do get this error
home/bienfait/nodejs/Node-Express/node_modules/finalhandler/index.js:256
  return typeof res.headersSent !== 'boolean'
                    ^

TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (/home/bienfait/nodejs/Node-Express/node_modules/finalhandler/index.js:256:21)
    at /home/bienfait/nodejs/Node-Express/node_modules/finalhandler/index.js:92:17
    at Function.handle (/home/bienfait/nodejs/Node-Express/node_modules/express/lib/application.js:170:5)
    at app (/home/bienfait/nodejs/Node-Express/node_modules/express/lib/express.js:39:9)
    at Object.<anonymous> (/home/bienfait/nodejs/Node-Express/index.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! node-express@1.0.0 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-express@1.0.0 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-express package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-express
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-express
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bienfait/nodejs/Node-Express/npm-debug.log

**Comment by marcus-sa** [comment]
https://github.com/expressjs/express/issues/3515
