### ISSUE TITLE
on-finished module is missing.

### ISSUE THREAD

**Issue by ChrisCooney** [pillarjs/finalhandler#22]
A missing module seems to be originating from this dependency. I get the following when I attempt to run the app, after a successful yarn install.

```
Error: Cannot find module 'on-finished'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chris/Projects/my-project/node_modules/finalhandler/index.js:17:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
```

**Comment by dougwilson** [comment]
Hi @ChrisCooney I'm not able to reproduce the issue locally. The module is listed in our `package.json` as far as I can tell as well. What changes do we need to make?

**Comment by dougwilson** [comment]
Closing due to no response.
